export const CATEGORIES = [
  { id: 'health', label: { en: 'Health', fa: 'سلامتی' }, icon: 'fitness_center', color: '#ef4444' },
  { id: 'study', label: { en: 'Study', fa: 'تحصیل' }, icon: 'school', color: '#3b82f6' },
  { id: 'work', label: { en: 'Work', fa: 'کار' }, icon: 'work', color: '#f59e0b' },
  { id: 'personal', label: { en: 'Personal', fa: 'شخصی' }, icon: 'person', color: '#10b981' },
];

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    goals: 'Goals',
    categories: 'Categories',
    settings: 'Settings',
    newGoal: '+ New Goal',
    streak: 'Streak',
    xp: 'XP Points',
    level: 'Level',
    activeGoals: 'Active Goals',
    completed: 'Completed',
    addProgress: 'Log Progress',
    delete: 'Delete',
    edit: 'Edit',
    title: 'Title',
    category: 'Category',
    target: 'Target',
    save: 'Save',
    cancel: 'Cancel',
    welcome: 'Welcome back!',
    noGoals: 'No goals found. Start by creating one!',
    confirmDelete: 'Are you sure you want to delete this goal?',
    yes: 'Yes',
    no: 'No',
    back: 'Back',
    status: 'Status',
    overallProgress: 'Overall Progress',
    activityHistory: 'Activity History',
    noActivity: 'No activity logged yet',
    unit: 'unit',
    active: 'Active',
    done: 'Done',
    pause: 'Pause',
    resume: 'Resume',
    stop: 'Stop',
    continue: 'Continue',
    goalDistribution: 'Goals Distribution by Category',
  },
  fa: {
    dashboard: 'داشبورد',
    goals: 'اهداف',
    categories: 'دسته‌بندی‌ها',
    settings: 'تنظیمات',
    newGoal: '+ هدف جدید',
    streak: 'توالی (روز)',
    xp: 'امتیاز تجربه',
    level: 'سطح',
    activeGoals: 'اهداف فعال',
    completed: 'انجام شده',
    addProgress: 'ثبت پیشرفت',
    delete: 'حذف',
    edit: 'ویرایش',
    title: 'عنوان',
    category: 'دسته‌بندی',
    target: 'هدف',
    save: 'ذخیره',
    cancel: 'لغو',
    welcome: 'خوش آمدید!',
    noGoals: 'هیچ هدفی یافت نشد. یکی بسازید!',
    confirmDelete: 'آیا مطمئن هستید که می‌خواهید این هدف را حذف کنید؟',
    yes: 'بله',
    no: 'خیر',
    back: 'بازگشت',
    status: 'وضعیت',
    overallProgress: 'پیشرفت کلی',
    activityHistory: 'تاریخچه فعالیت‌ها',
    noActivity: 'هنوز فعالیتی ثبت نشده است',
    unit: 'واحد',
    active: 'فعال',
    done: 'انجام شده',
    pause: 'توقف',
    resume: 'ادامه',
    stop: 'توقف',
    continue: 'ادامه',
    goalDistribution: 'توزیع اهداف بر اساس دسته‌بندی',
  },
};